### ISSUE TITLE
Assign teams to alert records

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-os#126]
### Scope

- We should be able to assign teams for alert records
- Fetch alerts by members should be on the basis of their team's assignment; it means, that the members return only those alerts if that alert is assigned to that member's team
- Remove `host-uuid` related logic we had applied
- Modify notification system on the basis of this logic

### Lifecycle:

`cpsprocessing` plugin needs to search for the appropriate teams by `name` and create/assign the alerts to the teams.

For example, there will be the following teams:
- Site1-Male
- Site1-Female
- Site2-Male
- Site2-Female

and an alert got happened in `Site1` on the `Male cubical`, `cpsprocessing` needs to create an alert and find the team by naming convention and attach that team. Do you agree with this?

**Comment by CanuckMarc** [comment]
@RaiBnod @NubeDev 

This solution seems workable, but not perfect.  

We would need to know the `teams` while creating the alerts, which is a bit of a pain.  I would again recommend using tags/meta-tags to deal with alert routing (if possible).

Situation 1 - Alert filtering based on `teams` - Manager wants to add a new `team`, which gets a variety of alerts.  To do this they would have to go to every alert, and add in this new `team` name to the alert.  No matter what, each alert has to be visited and modified. 

Scenario 2 - Alert filtering based on `tags/meta-tags` - Manager wants to add a new `team`, which gets a variety of alerts.  To do this they would select the alert `tags/meta-tags` that the new `team` subscribes to.  If all the tags already exist on the alerts, then there is no futher work needed.  If the tags don't exist already then the alerts need to have the tags added (same as for `teams` based alert filtering).  

So in many cases this Scenario 2 is more efficient and flexible.
