### ISSUE TITLE
Fix RubixOS Logs API

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-os#160]
The RubixOS Logs API was broken sometime recently.  It was working last week, and I requested that we be able to get more than 1000 lines of logs.  However, now it doesn't work at all....

```
POST: https://rb-cps.nube-iiot.com/ros/api/logs/create
BODY:
 {
    "service": "nubeio-rubix-os.service",
    "duration": 30
}

RESPONSE: 
{
    "uuid": "",
    "service": "nubeio-rubix-os.service",
    "duration": 30
}
```

**Comment by RaiBnod** [comment]
You have one extra parameter `number_of_lines: <int>`, by default, it's `0`.

Ticket it had been addressed: https://github.com/NubeIO/rubix-os/pull/142

See this attachment:

![image](https://github.com/NubeIO/rubix-os/assets/6800775/4e590948-6e44-4f25-a810-a8576a682b93)
