### ISSUE TITLE
teams user, alerts, tickets

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-os#63]
### workflow
- Add a team
- In the team set why types of alerts the want to subscribe to
- Add a new user to the team and enter the users email address
- Create a new alert by thing UUID and host UUID and alert type
- Create a new ticket based using the alert UUID
- Run a job to check the tickets and email the team as required
- Keep a list of email sent to the team

### team
- a team can subscribe to alert types

### ticket
- a ticket can have comments 

### user
- a user is added to a team
- a user can have option to mute from emails (maybe for a time period)

**Comment by RaiBnod** [comment]
More info:

- tickets: ticket will have either an association with `alert.uuid` or not (can create standalone ones as well)
- comments: ticket can have comments
- teams: ticket gets assigned with multiple teams
- we need to send emails to all of the assigned teams members (may be we can look this part after those above three implementation gets ready)
