### ISSUE TITLE
Make it easy to do API calls to `hosts` (edge devices)

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-os#75]
Please create a way so that it is easy to make API calls to other hosts from the cloud supervisor.

Example:  **Plugin needs to PING a host to check if it is currently online.** 

- In this case, the plugin already has the `host`.  
- Needs to deal with the authentication to the edge device.

Refrences:

- Host Proxy Code: https://github.com/NubeIO/rubix-os/blob/f09e69b6855dec125e70a353d18134bea7d913bf/api/hostproxy.go#L28

- Ping Host Function: https://github.com/NubeIO/rubix-os-client/blob/203a629bef591cfe5d38aaac6594bd4bc872a860/rubixoscli/base.go#L174C39-L174C39

**Comment by enjuthulung** [comment]
@CanuckMarc we already have edgecli.
- https://github.com/NubeIO/rubix-os/blob/ddf09a99df1fa15b6c80c07e3e6b5d4b3d29b52f/database/group.go#L87-L90
- https://github.com/NubeIO/rubix-os/blob/ddf09a99df1fa15b6c80c07e3e6b5d4b3d29b52f/database/host.go#L110-L111

**Comment by CanuckMarc** [comment]
@enjuthulung   Thanks!  

Can you please add a similar function which gets the edge device network properties?  

`cli.GetEdgeNetworking()` or something like that.

Reference: https://github.com/NubeIO/rubix-os-client/blob/203a629bef591cfe5d38aaac6594bd4bc872a860/rubixoscli/edgenetworks.go#L11
