### ISSUE TITLE
How do we install custom plugins/modules?

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-os#98]
We set up an RC for Inauro plugin testing, the RC has been updated to RubixOS v0.0.7.   

I cannot figure out how to install the `inauroazuresync` plugin.  I have entered the admin password (Helensburgh2508) in RubixCE settings.  

Aidan has suggested manually transfering a built plugin to the RC file system, but I cannot figure out how to generate an `arm7` plugin (like the `lorawan` plugin that is built by RubixOS and is already in the `plugins` directory).  

Please advise how to get the plugins installed.

**Comment by RaiBnod** [comment]
We use that plugin for a single client, so for now do these:

- Checkout your branch on `v2/master` in `rubix-ce`
- Add lines similar to this: https://github.com/NubeIO/rubix-ce/commit/795bf82624f21096279ba787424f3fced244908e
- Build `rubix-ce`
- Now you will see your plugin

We can maintain a branch `client/inauro` in `rubix-ce` for some time as `client/cps`. And to get all the latest changes, we **rebase** the content with `v2/master` **[rebase not merge, merge makes branches dirty]**.

**Comment by CanuckMarc** [comment]
Thanks!
